version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  cypress/run:
    executor:
      name: cypress/default
      node-version: "lts"
    steps:
      - cypress/install:
          package-manager: "yarn"
      - cypress/run-tests:
          start-command: "yarn run serve"
          cypress-command: "yarn run cy:run"
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          package-manager: yarn-berry
          name: Run Cypress
