version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-cypress:
    executor:
      name: cypress/default
      node-version: "lts"
    steps:
      - cypress/install:
          package-manager: "pnpm"
      - build:
          name: Build
          command: "pnpm run build"
      - cypress/run-tests:
          start-command: "pnpm run start"
          cypress-command: "pnpm run cy:run"
workflows:
  cypress:
    jobs:
      - run-cypress:
          name: Run Cypress
